# Generated by Django 3.2.4 on 2021-06-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0002_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='beat',
        ),
        migrations.DeleteModel(
            name='Beat',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
